name: yapf format

on:
  push:
    paths:
      - "**.py"

jobs:
  build:
    name: yapf format
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: format with yapf
        uses: AlexanderMelde/yapf-action@master
        with:
          args: -r -i -p ./src
      - name: commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "format: ${{ github.event.head_commit.message }}"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}